services:
  app-backend:
    build: 
      context:  ./app-backend
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_PASSWORD: suppers_dbpassword #in prod this would be a env secret
      BACKEND_PORT: 9000
      FRONTEND_PORT: 3000
    volumes:
      - ./app-backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "82:9000"
    depends_on:
      [suppers-db]

  app-frontend:
    build:
      context:  ./app-frontend
    environment:
      NODE_ENV: ${NODE_ENV}
      BACKEND_PORT: 9000
      FRONTEND_PORT: 3000
    volumes:
      - ./app-frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "81:3000"
  
  suppers-db:
    image: neo4j:latest
    volumes:
      - ./suppers-db/data:/data
      - ./suppers-db/import:/import
    environment:
        - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file 
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    secrets:
      - neo4j_auth_file

secrets:
  neo4j_auth_file:
    file: ./secrets/neo4j_auth.txt #Normally this would not be put in the git repo, however this is not for production