services:
  app-backend:
    build: 
      context:  ./app-backend
    environment:
      PY_ENV: ${PY_ENV}
      DB_PASSWORD: suppers_dbpassword #in prod this would be a env secret
      BACKEND_PORT: 9000
      FRONTEND_PORT: 3000
    volumes:
      - ./app-backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "82:9000"
    depends_on:
      suppers-db

  app-frontend:
    build:
      context:  ./app-frontend
    environment:
      NODE_ENV: ${NODE_ENV}
      BACKEND_PORT: 9000
      FRONTEND_PORT: 3000
    volumes:
      - ./app-frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      -"81:3000"
  
  suppers-db:
    image:  neo4j:latest
    volumes:
      - ./suppers-db/data:/data
      - ./suppers-db/import:/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4j_AUTH=neo4j/suppers_dbpassword #in prod this would be a env secret
    restart: always